name: medxpress
version: 1.0.0+1
publish_to: none
description: MedXprees is a e-commerce app for medicine
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies:

  #.------------Icons-------------#
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.7.0
  flutter_animated_icons: ^1.0.1

  #.------------State Management-------------#
  get: 4.6.6

  #.--------------Utility Packages--------------#
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.2.6
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.10+1
  pinput: ^4.0.0
  flutter_carousel_slider: ^1.1.0
  cached_network_image: ^3.3.1

  #.--------------Local Storage---------------#
  get_storage: ^2.1.1
  #.--------------Splash Screen--------------#
  flutter_native_splash: ^2.4.0
  #.--------------||---------------#
  #.--------------||---------------#
  #.--------------||---------------#
  #.--------------||---------------#
  #.--------------||---------------#
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onBoarding/
    - assets/logos/
    - assets/icons/social/
    - assets/icons/common/
    - assets/splash/
    - assets/images/home/
    - assets/icons/topCategory/
    - assets/icons/notification/
    - assets/icons/myOrder/
    - assets/icons/prescription/
    - assets/icons/myProfile/
    - assets/icons/bottomNavigationIcon/inActive/
    - assets/icons/bottomNavigationIcon/active/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic


